# Generated by Django 4.0.2 on 2022-02-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
