# Generated by Django 4.0.2 on 2022-02-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_celular_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nasc',
            field=models.DateField(verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(max_length=15, verbose_name='Sexo'),
        ),
    ]
